### ISSUE TITLE
resp is null

### ISSUE THREAD

**Issue by eugenepyvovarov** [PaulUithol/backbone-tastypie#1]
for some reason I get resp as null when creating a new object. Removing the check in line 25 fixed the code. Can you please tell why is it happening like this?

Thanks!

**Comment by PaulUithol** [comment]
Hmm, strange. Could you try and see what happens if you change that line to read 

```
if ( xhr.status === 201 && !resp ) ) { // 201 CREATED
```

? If that works for you, I'll update it to that. No idea why you'd get a `resp` as null though.

**Comment by eugenepyvovarov** [comment]
works for me, thanks
