### ISSUE TITLE
2 requests per 'create'

### ISSUE THREAD

**Issue by honza** [PaulUithol/backbone-tastypie#10]
I'm not sure if I like how you handle the creation of new objects. Why not require the user to add the `always_return_data` flag to the `Resource` definition and save a request per transaction?

[More here](http://django-tastypie.readthedocs.org/en/latest/resources.html#always-return-data).

I can submit a pull request to that effect, if you'd like.

Thanks

**Comment by PaulUithol** [comment]
Yeah, that may make more sense nowadays. That option didn't exist yet in Tastypie until a few months back though.

There may still be situations where the current behavior is preferable (for example, if you don't have full control over the API/server yourself, are stuck with an old version, etc). So maybe a setting to toggle between the current behavior and not overriding Backbone.sync at all?

**Comment by honza** [comment]
I was messing with this setup the other day and realized that if the data comes on create, the second request isn't necessary. I think I misread the comment in the source the first time around. It makes sense to leave it as is because not everyone will have `always_return_data` enabled. In any event, backbone-tastypie's `sync` method will do the right thing regardless of the backend settings.
