### ISSUE TITLE
Compatibility with other Backbone Sync (localStorage, original)

### ISSUE THREAD

**Issue by iplanwebsites** [PaulUithol/backbone-tastypie#11]
Hi Paul,

I'm trying to implement an APP that uses both the localStorage Sync, and an Ajax sync (tastypie).
It seems like some important methods get overridden, and including tastypie seems preventing me to use other sync methods.

It's possible to explicitly select a sync method on a collection or models basis (http://stackoverflow.com/questions/5096549/how-to-override-backbone-sync), but the JS here doesn't seem to play nicely with other Sync libararies. Maybe it's the extra prototype methods like "url" and such?

Do you have an idea of how it would be possible to run both the localStorage sync along the tastypie (ajax) sync?

**Comment by iplanwebsites** [comment]
Check out this commit for a proposed suggestion.
I'm far from mastering JS inheritance yet, and haven't managed to make it work (I suspect it's the way I copy the object), but I hope it helps you better understand the concern. Cheers,

https://github.com/iplanwebsites/backbone-tastypie/commit/be37cf490d02c0e33ecc889ee608084fdf956da8

**Comment by PaulUithol** [comment]
Sorry, I haven't been very active with tastypie lately. I'll look into this shortly.

**Comment by PaulUithol** [comment]
I don't think I really understand your problem here. Backbone-tastypie only overrides the default implementation for some methods, like `url`. You can still assign a different implementation on a per model or per collection basis if you want to?
