### ISSUE TITLE
Collections contain unused meta data, limiting collection results

### ISSUE THREAD

**Issue by hughes** [PaulUithol/backbone-tastypie#24]
When I use backbone-tastypie to get a collection of models, only the first 20 matching results are returned due to tastypie's default limit.

After `fetch` is called and these 20 models are returned, the query's meta data is stored in the collection's `meta` attribute. This records the `total_count`, as well as `offset`, and the `next` and `prev` urls. 

Currently, in my collections, I have to manually loop through `fetch`, changing the `offset` data and aggregating the results over and over until there are no more results. 

Is there a better way to do this? Would it be possible to change `fetch` to get all available results instead of just the first set?

**Comment by jordanvg** [comment]
If you specify the limit to be 0 when you fetch the collection, tastypie will skip pagination and return all objects: http://django-tastypie.readthedocs.org/en/latest/interacting.html#getting-a-collection-of-resources

For example:

``` javascript
this.collection.fetch( { data: { 'limit' : 0 } } );
```

**Comment by hughes** [comment]
That is definitely helpful. When I want to make use of pagination though, for example in a "infinite scroll" scenario, I guess I'd just have to make a new collection, manually specify the offset, and the append it to the original?

**Comment by jordanvg** [comment]
If you wanted to still use the exact collection that you fetched all the objects for you could make use of the Underscore methods for collections: http://backbonejs.org/#Collection-Underscore-Methods
