### ISSUE TITLE
Please tag the current release (0.2) so that this can be added to cdnjs.com

### ISSUE THREAD

**Issue by erikcw** [PaulUithol/backbone-tastypie#34]
I'm trying to Add backbone-tastypie to cdnjs.com, but their policy is to only accept tagged releases.  Can you tag the current 0.2 release in github so this library can be submitted?

For more info see:
https://github.com/cdnjs/cdnjs/pull/1560

Thanks!
Erik

**Comment by PaulUithol** [comment]
Thanks, finally got around to doing some maintenance on backbone-tastypie, have added the tag.
