### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by sunloverz** [PaulUithol/backbone-tastypie#36]
Sorry for offtop, trying to integrate django tastypie with backbone, and could somebody show me how backbone-tastypie works?

Backbone-tastypie overrides several Backbone methods for compatibility with django-tastypie. These mainly have to do with Backbone.sync, building urls for models and collections, and parsing data.

**Comment by karabijavad** [comment]
take a look at 
https://github.com/karabijavad/boricide-frontend/blob/master/js/app.js

as soon as you include the backbone-tastypie file, it will modify backbone as needed.

the app.js file i provided is included after backbone and backbone-tastypie are loaded

**Comment by sunloverz** [comment]
karabijavad , thank you  very much!
