### ISSUE TITLE
Wrong "main" value in bower.json

### ISSUE THREAD

**Issue by makmonty** [PaulUithol/backbone-tastypie#47]
The current `main` value in the bower.json file is `backbone_tastypie/tatic/js/backbone-tastypie.js` which is wrong, and makes auto-injections fails (wiredep)

**Comment by hacfi** [comment]
There is already a PR for that: https://github.com/PaulUithol/backbone-tastypie/pull/45

**Comment by makmonty** [comment]
Ok, I didn't find it. I close this issue.
