### ISSUE TITLE
Any solution for authentication types?

### ISSUE THREAD

**Issue by miratcan** [PaulUithol/backbone-tastypie#5]
Hi i am using backbone-tastypie, i need to add authentication parameters (username and apikey) to all urls. has backbone-tastypie solution for that? or any recomendations?

**Comment by PaulUithol** [comment]
I haven't actually really used these yet, so I'll need some more information on them. What are these parameters exactly, and how do you pass them in currently?

**Comment by chachra** [comment]
http://django-tastypie.readthedocs.org/en/latest/authentication_authorization.html#apikeyauthentication

They can be passed as GET or POST params. GET is easiest .... just append to each ajax call in a jQuery (or whatever javascript library you're using) by overriding globally in your code. This wouldn't require any code change here, but left for each developer to solve on their own.

Of course if this library could handle it (by say taking the key / username in the constructor) then it'll be nice too.
